// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var postsItemModel = PostsItemModel.FromJson(jsonString);
using Newtonsoft.Json;
using System;
namespace HW6pt2
{

    public partial class Dictionary
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("definition")]
        public string Definition { get; set; }

        [JsonProperty("example")]
        public string Example { get; set; }
        
        [JsonProperty("image_url")]
        public Uri ImageUrl { get; set; }

        [JsonProperty("emoji")]
        public string Emoji { get; set; }
    }
}
   